---
title: "finalproj_exploration"
author: "Juliet Rowe"
date: "2023-11-26"
output: github_document
---

Load libraries
```{r}
library(tidyverse)
library(ggplot2)

```

Load rat data
```{r}
rat_sightings <- read.csv("data/Rat_Sightings_20231121.csv") |>
  janitor::clean_names() |>
    separate(closed_date, into = c("month", "day", "year_date"), sep = "/") |>
  separate(year_date, into = c("year", "time"), sep = " ") |>  
  select(-created_date, -agency, -agency_name, -complaint_type, -descriptor, -landmark, -facility_type, -park_facility_name, -vehicle_type, -taxi_company_borough, -taxi_pick_up_location, -bridge_highway_name, -road_ramp, -bridge_highway_segment, -bridge_highway_direction) |>  
  mutate(year = as.numeric(as.character(year)), month = as.numeric(as.character(month)), day = as.numeric(as.character(day)))

rat_sightings <- rat_sightings |>
  filter(year == 2016 & month >=1) | (year >= 2016 & year <= 2023) | (year == 2023 & month <=11) 
```


Load weather data
```{r}
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```



Rat sightings by latitude and longitude
```{r}
rat_sightings |>
  ggplot(aes(x=-latitude, y=longitude)) + geom_point()
```

