---
title: "finalproj_exploration"
author: "Juliet Rowe"
date: "2023-11-26"
output: github_document
---

Load libraries
```{r}
library(tidyverse)
library(ggplot2)
library(plotly)

```

Load rat data
```{r}
sightings = read_csv('data/Rat_Sightings_20231121.csv') |> 
  janitor::clean_names() |> 
  separate(created_date, into=c("month","e", "day","f", "year", "g", "time"), sep=c(2,3,5,6,10,11)) |> 
  select(-e,-f,-g) |> 
  mutate(date = paste(year, month, day, sep=""), 
         date = as.numeric(date)) |>  
  filter(date <= 20231031, date >= 20160101, !incident_zip <= 10000, !incident_zip >11697, !borough %in% c("Unspecified", NA)) |> 
  select(-agency, -agency_name, -complaint_type, -descriptor, -landmark, -facility_type, -park_facility_name, -vehicle_type, -taxi_company_borough, -taxi_pick_up_location, -bridge_highway_name, -road_ramp, -bridge_highway_segment, -bridge_highway_direction) |> select(unique_key, date, year, month, day, everything())
```


Load weather data
```{r}
weather_df = rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2016-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


Merge weather and rat data
```{r}
sightings$date <- as.Date(as.character(sightings$date), format = "%Y%m%d")

rat_weather =
  right_join(sightings, weather_df, by="date")
```



Rat sightings by latitude and longitude
```{r}


plot_ly(rat_weather, x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
        color = ~borough, colors = c("blue", "red", "green", "purple", "orange")) |>
  layout(title = "Rat Sightings by Latitude and Longitude",
         xaxis = list(title = "Longitude"),
         yaxis = list(title = "Latitude"))



rat_weather |>
  filter(borough == "MANHATTAN") |>
  sample_n(10000) |> 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
        color = ~tmax, alpha=0.8) |>
  layout(title = "Rat Sightings by Latitude, Longitude, and Maximum Temperature",
         xaxis = list(title = "Longitude"),
         yaxis = list(title = "Latitude"))
```



Rat sightings per day
```{r}
rat_weather |>
  mutate(year = as.factor(year)) |>
  group_by(date) |>
  summarize(count = n(), year) |>  
  ggplot(aes(x = date, y = count, color=year)) +
  geom_point(alpha = 0.25) + 
  labs(title = "Time Series: Rat Sightings Over Time",
       x = "Date",
       y = "Number of Rat Sightings")
```


Rat sightings versus precipitation
```{r}

rat_weather |>
  filter(prcp != 1811) |>
  mutate(prcp = as.factor(prcp)) |>
  group_by(date, prcp) |>
  summarize(count = n()) |>
  mutate(prcp_numeric = as.numeric(as.character(prcp))) |>
  ggplot(aes(x = prcp_numeric, y = count)) +
  geom_point(alpha = 0.25) +
  geom_smooth(method = "glm", formula = y ~ x, se = FALSE) +
  scale_x_continuous(breaks = unique(as.numeric(as.character(rat_weather$prcp))),
                     labels = unique(rat_weather$prcp)) +
  labs(title = "Scatter Plot: Precipitation vs. Rat Sightings",
       x = "Precipitation (inches)",
       y = "Number of Rat Sightings")

```


by year
```{r}
rat_weather |>
  group_by(date) |>
  summarize(count = n(), year, tmax) |>
  ggplot(aes(x = tmax, y = count, color = year)) + 
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE, color="black") + 
  facet_grid(. ~ year) +
  labs(title = "Maximum Temperature vs. Rat Sightings by Year",
       x = "Maximum temperature (degrees Celsius)",
       y = "Number of Rat Sightings")



```

 by month
```{r}
rat_weather |>
  group_by(month) |>
  summarize(count = n(), month, tmax) |>
  ggplot(aes(x = tmax, y = count, color = month)) + 
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ month) +
  labs(title = "Maximum Temperature vs. Rat Sightings by Month",
       x = "Maximum temperature (degrees Celsius)",
       y = "Number of Rat Sightings")

```
 
 